; The pool name (group of processes): [www] is the default name.
[www]

; Theses lines define which Linux user and group will execute the PHP scripts.
; By using www-data, the web server is confined. Even if compromised, the attacker can only
; access files that www-data is allowed to see.
; This follows the User Private Group convention in Linux.
; The user and group are created automatically when we install a web server package.
; We can find them in the system identity files :
; - /etc/passwd : Show the www-data user details
; - /etc/group : Show the www-data group details
user = www-data
group = www-data

; The communication point
; This tells PHP-FPM where to listen for incoming requests from Nginx.
listen = 0.0.0.0:9000

; The process Manager Mode
; Dynamic means PHP-FPM will adjust the number of child processes
; based on how much traffic our website is receiving
pm = dynamic

; --- Dynamix Rules ---

; the absolute ceiling, it's the maximum number of simultaneous processes allowed.
pm.max_children = 10

; The number of child processes created on startup.
pm.start_servers = 2

; The desired minimum number of idle server processes.
pm.min_spare_servers = 2

; The desired maximum number of idle server processes.
pm.max_spare_servers = 5

; --- Stability & Memory Management ---

; Once an individual child process has handled 500 requests, it is killed and restarted.
; This prevents "Memory Bloat" (leaks) and ensures a clean memory state regularly.
pm.max_requests = 500

; Allow variables from .env to be read
clear_env = no
